'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import type { WorkbenchMessage } from '@/components/agent-lab/workbench/types';
import { AVAILABLE_MODELS } from '@/components/agent-lab/workbench/types';
import { classifyToolCall, type ToolKind } from '@/lib/boost/classify';
import type { ChartDSLSpec } from '@/lib/studio/chart-dsl';
import type { SemanticQuery } from '@/lib/semantic/types';

export interface QueryResult {
  columns: { name: string; type_name: string }[];
  rows: Record<string, unknown>[];
  sql: string;
  rowCount: number;
  truncated: boolean;
  persistedId?: string;
  cachedProfiles?: import('@/lib/studio/types').ColumnProfile[];
  cachedSpecs?: import('@/lib/studio/types').ChartSpec[];
  cachedChartOverrides?: Record<number, Record<string, import('@/lib/studio/types').ChartSpec>>;
  cachedActiveResultIndex?: number;
}

// Represents a semantic chart result surfaced in the Inspector chat thread.
// These are generated by the emit_semantic_chart LLM tool and carry the full
// SemanticQuery so the chart can be promoted to platform_charts.
export interface SemanticChartMessage {
  id: string;
  kind: 'semantic_chart';
  chartDsl: ChartDSLSpec;
  semanticQuery: SemanticQuery;
  sql: string;
  /** Pre-compiled ECharts option from the pipeline — used directly by StudioChart */
  echartsOption: object;
  timestamp: number;
}

export type { ToolKind } from '@/lib/boost/classify';

export type TurnOutcome = 'completed' | 'truncated' | 'errored';

export interface RunMetric {
  durationMs: number;
  tokenCount: number;
  modelName: string;
  modelKey: string;
  inputTokens: number;
  outputTokens: number;
  loopCount: number;
  firstTokenMs: number | null;
  contextMode: 'harvested' | 'warehouse_only';
  toolCalls: { name: string; durationMs: number; status: 'success' | 'error'; kind: ToolKind; sqlExcerpt?: string | null }[];
  turnIndex: number;
  outcome: TurnOutcome;
}

interface UseInspectorChatOptions {
  sessionId: string | null;
  contextMode?: 'harvested' | 'warehouse_only';
}

interface UseInspectorChatReturn {
  messages: WorkbenchMessage[];
  isStreaming: boolean;
  error: string | null;
  sessionLoadError: string | null;
  suggestions: string[];
  selectedModel: string;
  setSelectedModel: (model: string) => void;
  interrupted: boolean;
  completionMeta: Record<string, { durationMs: number; tokenCount: number; modelName: string }>;
  runMetrics: Record<string, RunMetric>;
  sessionId: string | null;
  queryResults: QueryResult[];
  semanticChartMessages: SemanticChartMessage[];
  send: (content: string) => void;
  abort: () => void;
  reset: () => void;
  editMessage: (messageId: string) => { content: string } | null;
}

export function useInspectorChat({ sessionId, contextMode = 'harvested' }: UseInspectorChatOptions): UseInspectorChatReturn {
  const [queryResults, setQueryResults] = useState<QueryResult[]>([]);
  const [semanticChartMessages, setSemanticChartMessages] = useState<SemanticChartMessage[]>([]);
  const [previewModel, setPreviewModel] = useState(AVAILABLE_MODELS[1].key);

  // Inspector owns its session id locally (see currentSessionId below). This ref
  // mirrors it for use inside async stream callbacks. Init matches the prop, which
  // is exactly the initial value the removed workbench hook exposed on mount.
  const sessionIdRef = useRef<string | null>(sessionId);

  const modelRef = useRef<string>(previewModel);
  useEffect(() => { modelRef.current = previewModel; }, [previewModel]);

  const contextModeRef = useRef<'harvested' | 'warehouse_only'>(contextMode);
  useEffect(() => { contextModeRef.current = contextMode; }, [contextMode]);

  const [localMessages, setLocalMessages] = useState<WorkbenchMessage[]>([]);
  const [isStreaming, setIsStreaming] = useState(false);
  const [interrupted, setInterrupted] = useState(false);
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [completionMeta, setCompletionMeta] = useState<Record<string, { durationMs: number; tokenCount: number; modelName: string }>>({});
  const [runMetrics, setRunMetrics] = useState<Record<string, RunMetric>>({});
  const [currentSessionId, setCurrentSessionId] = useState<string | null>(sessionId);
  useEffect(() => { sessionIdRef.current = currentSessionId; }, [currentSessionId]);
  const [sessionLoadError, setSessionLoadError] = useState<string | null>(null);
  const autosaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const streamStartRef = useRef<number | null>(null);
  const firstTokenRef = useRef<number | null>(null);
  const abortControllerRef = useRef<AbortController | null>(null);
  const turnCountRef = useRef<number>(0);

  // Per-stream accumulator for tool calls (reset each doSend)
  const pendingToolCallsRef = useRef<{ name: string; durationMs: number; status: 'success' | 'error'; kind: ToolKind; sqlExcerpt?: string | null }[]>([]);

  let msgIdCounter = 0;
  function nextMsgId(): string {
    return `insp_${Date.now()}_${++msgIdCounter}`;
  }

  // Load session on mount if sessionId provided
  useEffect(() => {
    if (!sessionId) return;
    fetch(`/api/agent-lab/workbench/sessions/${sessionId}`)
      .then(r => {
        if (!r.ok) throw new Error(`Session load failed: ${r.status}`);
        return r.json();
      })
      .then((data: { session?: { id: string; title?: string; messages?: WorkbenchMessage[]; progress?: { last_model?: string } } } | null) => {
        if (!data?.session) { setSessionLoadError(`Session not found (id: ${sessionId})`); return; }
        const s = data.session;
        setLocalMessages(s.messages || []);
        if (s.progress?.last_model && AVAILABLE_MODELS.some(m => m.key === s.progress!.last_model)) {
          setPreviewModel(s.progress.last_model as string);
        }
        setCurrentSessionId(s.id);
        setSessionLoadError(null);

        fetch(`/api/studio/results?sessionId=${s.id}`)
          .then(r => r.ok ? r.json() : null)
          .then((res: { results?: Array<{ id: string; seq: number; sql: string; columns: QueryResult['columns']; rows: QueryResult['rows']; row_count: number; truncated: boolean; profiles?: unknown; specs?: unknown; chart_overrides?: unknown; active_result_index?: number | null }> } | null) => {
            if (res?.results?.length) {
              const hydrated: QueryResult[] = res.results.map(r => ({
                columns: r.columns as QueryResult['columns'],
                rows: r.rows as QueryResult['rows'],
                sql: r.sql,
                rowCount: r.row_count,
                truncated: r.truncated,
                persistedId: r.id,
                cachedProfiles: r.profiles ? r.profiles as QueryResult['cachedProfiles'] : undefined,
                cachedSpecs: r.specs ? r.specs as QueryResult['cachedSpecs'] : undefined,
                cachedChartOverrides: r.chart_overrides
                  ? r.chart_overrides as QueryResult['cachedChartOverrides']
                  : undefined,
                cachedActiveResultIndex: typeof r.active_result_index === 'number'
                  ? r.active_result_index
                  : undefined,
              }));
              setQueryResults(hydrated);
            }
          })
          .catch(() => {/* non-fatal */});
      })
      .catch((err: unknown) => {
        setSessionLoadError(err instanceof Error ? err.message : 'Failed to load session');
      });
  }, [sessionId]); // eslint-disable-line react-hooks/exhaustive-deps

  // Autosave
  useEffect(() => {
    if (!currentSessionId) return;
    if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
    autosaveTimer.current = setTimeout(() => {
      fetch(`/api/agent-lab/workbench/sessions/${currentSessionId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: localMessages, last_model: modelRef.current }),
      }).catch(() => {});
    }, 2000);
    return () => { if (autosaveTimer.current) clearTimeout(autosaveTimer.current); };
  }, [currentSessionId, localMessages]);

  const doSend = useCallback(async (content: string) => {
    const sid = sessionIdRef.current;
    const model = modelRef.current;
    const ctxMode = contextModeRef.current;

    const userMsgId = nextMsgId();
    const assistantMsgId = nextMsgId();
    const now = Date.now();
    const turnIndex = ++turnCountRef.current;

    pendingToolCallsRef.current = [];

    const userMsg: WorkbenchMessage = { id: userMsgId, role: 'user', content, timestamp: now, turnNumber: 0 };
    const assistantMsg: WorkbenchMessage = { id: assistantMsgId, role: 'assistant', content: '', timestamp: now, turnNumber: 0 };

    setLocalMessages(prev => [...prev, userMsg, assistantMsg]);
    setIsStreaming(true);
    setInterrupted(false);
    setSuggestions([]);
    streamStartRef.current = Date.now();
    firstTokenRef.current = null;

    const ctrl = new AbortController();
    abortControllerRef.current = ctrl;

    try {
      const allMessages = await new Promise<WorkbenchMessage[]>(resolve => {
        setLocalMessages(prev => { resolve(prev); return prev; });
      });

      const resp = await fetch('/api/inspector/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId: sid,
          messages: [...allMessages.filter(m => m.id !== assistantMsgId), userMsg],
          model,
          contextMode: ctxMode,
        }),
        signal: ctrl.signal,
      });

      if (!resp.ok || !resp.body) {
        setError(`Stream error: ${resp.status}`);
        setIsStreaming(false);
        return;
      }

      const reader = resp.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      let rawContent = '';
      let loopCount = 0;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() ?? '';

        for (const line of lines) {
          if (!line.startsWith('data: ')) continue;
          const raw = line.slice(6).trim();
          if (!raw) continue;

          let event: Record<string, unknown>;
          try { event = JSON.parse(raw); } catch { continue; }

          switch (event.type) {
            case 'text':
              // Capture time-to-first-token on first text delta
              if (firstTokenRef.current === null && streamStartRef.current !== null) {
                firstTokenRef.current = Date.now() - streamStartRef.current;
              }
              rawContent += event.delta as string;
              setLocalMessages(prev => {
                const updated = [...prev];
                const idx = updated.findIndex(m => m.id === assistantMsgId);
                if (idx >= 0) updated[idx] = { ...updated[idx], content: sanitize(rawContent) };
                return updated;
              });
              break;

            case 'text_replace':
              rawContent = event.text as string;
              setLocalMessages(prev => {
                const updated = [...prev];
                const idx = updated.findIndex(m => m.id === assistantMsgId);
                if (idx >= 0) updated[idx] = { ...updated[idx], content: sanitize(rawContent) };
                return updated;
              });
              break;

            case 'loop_start':
              loopCount = (event.loop as number) ?? loopCount + 1;
              break;

            case 'tool_call_suggested':
            case 'tool_call_running':
            case 'tool_call_result':
            case 'tool_call_error':
              setLocalMessages(prev => {
                const updated = [...prev];
                const idx = updated.findIndex(m => m.id === assistantMsgId);
                if (idx < 0) return prev;
                const msg = updated[idx];
                const existing = msg.toolCalls ?? [];
                if (event.type === 'tool_call_suggested') {
                  if (existing.some(tc => tc.callId === event.callId)) return updated;
                  updated[idx] = { ...msg, toolCalls: [...existing, { callId: event.callId as string, toolId: event.toolId as string, toolName: event.toolName as string, status: 'suggested' as const }] };
                } else if (event.type === 'tool_call_running') {
                  updated[idx] = { ...msg, toolCalls: existing.map(tc => tc.callId === event.callId ? { ...tc, status: 'running' as const, input: event.input as Record<string, unknown> } : tc) };
                } else if (event.type === 'tool_call_result') {
                  updated[idx] = { ...msg, toolCalls: existing.map(tc => tc.callId === event.callId ? { ...tc, status: 'success' as const, output: event.output, durationMs: event.durationMs as number } : tc) };
                  const toolName = existing.find(tc => tc.callId === event.callId)?.toolName ?? '';
                  const sqlExcerpt = (existing.find(tc => tc.callId === event.callId)?.input as Record<string, unknown> | undefined)?.args
                    ? ((existing.find(tc => tc.callId === event.callId)?.input as Record<string, unknown>)?.args as Record<string, unknown>)?.statement as string | undefined
                    : undefined;
                  const kind = classifyToolCall({ tool: toolName, sql: sqlExcerpt, status: 'success' });
                  pendingToolCallsRef.current.push({
                    name: toolName,
                    durationMs: (event.durationMs as number) ?? 0,
                    status: 'success',
                    kind,
                    sqlExcerpt: sqlExcerpt ? (sqlExcerpt as string).slice(0, 120) : null,
                  });
                } else {
                  updated[idx] = { ...msg, toolCalls: existing.map(tc => tc.callId === event.callId ? { ...tc, status: 'error' as const, error: event.error as string } : tc) };
                  const toolName = existing.find(tc => tc.callId === event.callId)?.toolName ?? '';
                  const kind = classifyToolCall({ tool: toolName, status: 'error' });
                  pendingToolCallsRef.current.push({
                    name: toolName,
                    durationMs: 0,
                    status: 'error',
                    kind,
                  });
                }
                return updated;
              });
              break;

            case 'query_result': {
              const qr: QueryResult = {
                columns: event.columns as QueryResult['columns'],
                rows: event.rows as Record<string, unknown>[],
                sql: event.sql as string,
                rowCount: event.rowCount as number,
                truncated: event.truncated as boolean,
              };
              setQueryResults(prev => {
                const seq = prev.length;
                const sid2 = sessionIdRef.current;
                if (sid2) {
                  fetch('/api/studio/results', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                      sessionId: sid2,
                      seq,
                      sql: qr.sql,
                      columns: qr.columns,
                      rows: qr.rows,
                      rowCount: qr.rowCount,
                      truncated: qr.truncated,
                    }),
                  })
                    .then(r => r.ok ? r.json() as Promise<{ id: string }> : null)
                    .then(res => {
                      if (res?.id) {
                        setQueryResults(curr =>
                          curr.map((r, i) => i === seq ? { ...r, persistedId: res.id } : r),
                        );
                      }
                    })
                    .catch(() => {/* non-fatal */});
                }
                return [...prev, qr];
              });
              break;
            }

            case 'done': {
              const usage = event.usage as { inputTokens?: number; outputTokens?: number } | undefined;
              const durationMs = streamStartRef.current != null ? Date.now() - streamStartRef.current : 0;
              const firstTokenMs = firstTokenRef.current;
              streamStartRef.current = null;
              firstTokenRef.current = null;

              const inputTokens = usage?.inputTokens ?? 0;
              const outputTokens = usage?.outputTokens ?? 0;
              const totalTokens = inputTokens + outputTokens;
              const finalLoopCount = (event.loops as number) ?? loopCount;
              const modelKey = model;
              const modelLabel = AVAILABLE_MODELS.find(m => m.key === modelKey)?.label ?? modelKey;
              // Prefer server-confirmed contextMode over local ref (server is source of truth)
              const confirmedCtxMode = (event.contextMode as 'harvested' | 'warehouse_only') ?? ctxMode;

              // B1: populate toolCalls with kind from server trajectory if available
              type ServerTrajEntry = { seq: number; tool: string; sqlExcerpt: string | null; status: 'success' | 'error'; durationMs: number; kind: ToolKind };
              const serverTrajectory = event.toolTrajectory as ServerTrajEntry[] | undefined;
              let finalToolCalls: typeof pendingToolCallsRef.current;
              if (serverTrajectory && Array.isArray(serverTrajectory) && serverTrajectory.length > 0) {
                finalToolCalls = serverTrajectory.map(t => ({
                  name: t.tool,
                  durationMs: t.durationMs,
                  status: t.status,
                  kind: t.kind,
                  sqlExcerpt: t.sqlExcerpt,
                }));
              } else {
                finalToolCalls = [...pendingToolCallsRef.current];
              }

              // B1: determine outcome from server or derive conservatively
              const serverOutcome = event.outcome as TurnOutcome | undefined;
              const outcome: TurnOutcome = serverOutcome ?? (event.limitReached ? 'truncated' : 'completed');

              setCompletionMeta(prev => ({
                ...prev,
                [assistantMsgId]: { durationMs, tokenCount: totalTokens, modelName: modelLabel },
              }));

              setRunMetrics(prev => ({
                ...prev,
                [assistantMsgId]: {
                  durationMs,
                  tokenCount: totalTokens,
                  modelName: modelLabel,
                  modelKey,
                  inputTokens,
                  outputTokens,
                  loopCount: finalLoopCount,
                  firstTokenMs,
                  contextMode: confirmedCtxMode,
                  toolCalls: finalToolCalls,
                  turnIndex,
                  outcome,
                },
              }));

              pendingToolCallsRef.current = [];
              break;
            }

            case 'suggestions':
              setSuggestions(Array.isArray(event.items) ? event.items as string[] : []);
              break;

            case 'semantic_chart_result': {
              const scm: SemanticChartMessage = {
                id: `scm_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
                kind: 'semantic_chart',
                chartDsl: event.spec as ChartDSLSpec,
                semanticQuery: event.semanticQuery as SemanticQuery,
                sql: event.sql as string,
                echartsOption: event.option as object,
                timestamp: Date.now(),
              };
              setSemanticChartMessages(prev => [...prev, scm]);
              break;
            }

            case 'error':
              setError(event.message as string);
              break;

            case 'loop_limit_reached':
              break;
          }
        }
      }
    } catch (err: unknown) {
      if (err instanceof Error && err.name === 'AbortError') {
        setInterrupted(true);
      } else {
        setError(err instanceof Error ? err.message : 'Stream failed');
      }
    } finally {
      setIsStreaming(false);
      abortControllerRef.current = null;
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const send = useCallback((content: string) => {
    setSuggestions([]);
    setInterrupted(false);
    setError(null);

    if (!currentSessionId) {
      fetch('/api/inspector/sessions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title: content.slice(0, 80), surface: 'inspector', context_mode: contextModeRef.current }),
      })
        .then(r => r.json())
        .then((data: { session: { id: string } }) => {
          const id = data.session.id;
          setCurrentSessionId(id);
          sessionIdRef.current = id;
          // Persist model selection immediately
          fetch(`/api/agent-lab/workbench/sessions/${id}`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ last_model: modelRef.current }),
          }).catch(() => {});
          doSend(content);
        })
        .catch(() => { doSend(content); });
      return;
    }

    doSend(content);
  }, [currentSessionId, doSend]); // eslint-disable-line react-hooks/exhaustive-deps

  const abort = useCallback(() => {
    abortControllerRef.current?.abort();
    setIsStreaming(false);
    setInterrupted(true);
  }, []);

  const reset = useCallback(() => {
    abortControllerRef.current?.abort();
    setLocalMessages([]);
    setQueryResults([]);
    setSemanticChartMessages([]);
    setSuggestions([]);
    setInterrupted(false);
    setIsStreaming(false);
    setCurrentSessionId(null);
    sessionIdRef.current = null;
    setError(null);
    setCompletionMeta({});
    setRunMetrics({});
    turnCountRef.current = 0;
  }, []);

  const editMessage = useCallback((messageId: string): { content: string } | null => {
    const idx = localMessages.findIndex(m => m.id === messageId);
    if (idx === -1) return null;
    const msg = localMessages[idx];
    if (msg.role !== 'user') return null;
    setLocalMessages(localMessages.slice(0, idx));
    setInterrupted(false);
    setSuggestions([]);
    return { content: msg.content };
  }, [localMessages]);

  const handleModelChange = useCallback((model: string) => {
    setPreviewModel(model);
  }, []);

  return {
    messages: localMessages,
    isStreaming,
    error,
    sessionLoadError,
    suggestions,
    selectedModel: previewModel,
    setSelectedModel: handleModelChange,
    interrupted,
    completionMeta,
    runMetrics,
    sessionId: currentSessionId,
    queryResults,
    semanticChartMessages,
    send,
    abort,
    reset,
    editMessage,
  };
}

function sanitize(text: string): string {
  return text
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<\/?thinking>/gi, '')
    .replace(/<query_result>[\s\S]*?<\/query_result>/gi, '')
    .replace(/<(agent_config|tool_config|schema_config|prompt_config|bus_contract_config)[\s\S]*?<\/\1>/gi, '')
    .trim();
}
